services:
  - type: web
    name: quizloop-api
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: Firebase__ProjectId
        value: quizloop-prod
